name: students
services:
  ic:
    public: true
    image: 'okteto.dev/demo-gec'
    build: .
    replicas: 1
    ports:
      - 6969
    resources:
      cpu: 2
      memory: 4Gi
      storage: 2Gi
    volumes:
      - /data
    environment:
      - environment=development
