name: students
services:
  ic:
    public: true
    image: 'okteto.dev/students'
    build: .
    replicas: 1
    ports:
      - 6969
    resources:
      cpu: 1
      memory: 1Gi
      storage: 2Gi
    volumes:
      - /Engineering
    environment:
      - environment=development
