name: gec
services:
  ic:
    image: 'okteto.dev/ic'
    build: .
    replicas: 1
    ports:
      - 6969
    resources:
      cpu: 2
      memory: 4Gi
      storage: 3Gi
    volumes:
      - /data
    environment:
      - environment=development
